### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by TLi347** [hanq0212/VAE_pytorch#1]
Hi,
When I run main.py, it reported this error:
      ~/VAE_pytorch/models/vanilla_vae.py", line 92, in weight_init
          kaiming_init()
      TypeError: kaiming_init() missing 1 required positional argument: 'm'

**Comment by HAN-oQo** [comment]
Hi,
I fixed that error. Can you try it again, please?
You may change the config file.
Thank you.

**Comment by TLi347** [comment]
Thanks, it works now!
